<a href="https://colab.research.google.com/github/skomandooru/pdsnd_github/blob/master/DS%20200%20Komandooru_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python Programming for Data Science

 - This notebook provides an introduction to programming with python. 
 - The target is to provide background concepts that you need to leverage python for your data science algorithms, models, and visualizations. 
 
## Resources
 
### 1. Datascience Package - Table
 - http://data8.org/datascience/tutorial.html
 - http://data8.org/datascience/tables.html
 - http://data8.org/fa16/ref.html


### 2. Course Text
 - https://jakevdp.github.io/PythonDataScienceHandbook/


### 3. Markdown
 - https://www.markdownguide.org/basic-syntax/

### 4. My name is Surya Komandooru  
       My partner's name is Donggeon Lee

### Expressions in Python
Expression Type	Operator	Example	Value
- Addition (+)
- Subtraction	(-)
- Multiplication	(*)
- Division	(/)
- Remainder	(%)
- Exponentiation	(**)

See some **examples** below

In [ ]:
x = 5
y = 3

print("Addition: %d" % (x + y))
print("Subtraction: %d" % (x - y))
print("Multiplication: %d" % (x * y))
print("Division: %d" % (x / y))
print("Remainder: %d" % (x % y))
print("Exponentiation: %d" % (x ** y))


Addition: 8
Subtraction: 2
Multiplication: 15
Division: 1
Remainder: 2
Exponentiation: 125


### Naming variables
- Ensure that variables are named in lowercase in python. For example services, persons, year
- Use the underscore to catenate more complex names. For example date_of_birth
- Keep variable names very descriptive of the values they contain. For example sales_tax

In [ ]:
person_lastname = "Lee"
person_firstname = "Donggeon"
age = 20
country_tax_rate = 0.13

print("%s %s is %d. His tax rate is %f" % (person_firstname, person_lastname.lower(), age, country_tax_rate))

Donggeon lee is 20. His tax rate is 0.130000


### Using built-in functions
Python supports many built-in function for your transformations. 
These include rounding off numbers, calculating max, min, averages, etc.

In [ ]:
our_list = [1,3,4,6,10] # list of numbers

# Return the max, min, and averages to our list
print("max:%d, min:%d" % (max(our_list), min(our_list)))

### User defined functions
These are functions that provides specific functionality to your analytics.
In the example below, we create a simply UDF for calculating averages of a list

In [ ]:
def average(list):
    return sum(list) / len(list)

# Calculate the average of our list
avg = average(our_list)

# Print the average
print("Average = ", round(avg, 3))

### Import modules
External modules provide us with extended functionalities. 

**import** statements allow us to access functions from external libraries. In the example below, we will use the log function from the math library to compute log

In [ ]:
import math
print("Square root of 625: %d." % math.sqrt(625))
print("Log 16: %f." % round(math.log(16), 2))
print("Log 64 base 2: %d" % math.log(64, 2))

Square root of 625: 25.
Log 16: 2.770000.
Log 64 base 2: 6


### Importing specific functions
In the example above, we imported the entire math module. Sometimes it's preferable to import specific functions from module.

This example shows the same example above but with specific imports

***General syntax*** is from <module> import function1, function2, ..., functionn


In [ ]:
from math import sqrt, log # Import the functions from the math module

print("Square root of 625: %d." % sqrt(625))
print("Log 16: %f." % round(log(16), 2))
print("Log 64 base 2: %d" % log(64, 2))

# this is a lot cleaner than the previous example.

Square root of 625: 25.
Log 16: 2.770000.
Log 64 base 2: 6


### Working with Collection
We will work a lot with collections. They contain group values that can be referenced as a varible.
See some examples of collections in python

In [ ]:
number_collection = [1,2,3,4,5]
number_collection

In [ ]:
string_collection = ["one","two","three","four","five"]
string_collection

In [ ]:
mixed_type_collection = [1, 1.2, "one point 3", 3.4, 5]
mixed_type_collection

### Importing Packages
Sometimes we need to import packages to our notebook. For most of our exercies, we will be using the ***datascience*** package.

Use the pip install command to install a new package to your note

In [ ]:
!pip install datascience # Install the package

# Install all the packages from the data science module
from datascience import *

     |████████████████████████████████| 71kB 2.8MB/s 
  Created wheel for folium: filename=folium-0.2.1-cp36-none-any.whl size=79980 sha256=515570f10f6e8b48398550fe0c81e4b34c80a44b3edf421ca8b841341dcac85a
  Stored in directory: /root/.cache/pip/wheels/b8/09/f0/52d2ef419c2aaf4fb149f92a33e0008bdce7ae816f0dd8f0c5
Successfully built folium
  Found existing installation: folium 0.8.3
    Uninstalling folium-0.8.3:
      Successfully uninstalled folium-0.8.3


/usr/local/lib/python3.6/dist-packages/datascience/tables.py:17: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use('agg', warn=False)
/usr/local/lib/python3.6/dist-packages/datascience/util.py:10: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use('agg', warn=False)


In [ ]:
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'], dtype='<U12')

In [ ]:
baseline_high = 12.64
highs = make_array(baseline_high - 0.776, 
                   baseline_high - 0.086,
                   baseline_high + 0.254, 
                   baseline_high + 0.946)
highs

array([11.864, 12.554, 12.894, 13.586])

In [ ]:
# Perform computations on the arrays
(9/5) * highs + 32

array([53.3552, 54.5972, 55.2092, 56.4548])

### Perform basic statistical analysis on the numpy array
The following functions are supported: max, min, sum, len, np.std (standard deviation), np.diff, np.sqrt

In [ ]:
highs.size

4

In [ ]:
highs.sum()

50.897999999999996

In [ ]:
highs.mean()

12.724499999999999

In [ ]:
highs.std()

0.6205729207756329

### Python List vs. Numpy Array

***Numpy*** is a core library for scientific computing in Python. Unlike python collection, a numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers.

Some common numpy functions that return scalar values:
- ***np.prod***: Multiply all the elements of an array
- ***np.sum***: Add all the elements
- ***np.all***: Test if all the elements are greater than zero
- ***np.any***: Test if any of the elements is greater than zero
- ***np.count_nonzero***: Count the number of non-zero elements

Some of the common numpy functions that returns an array:
- **np.diff**: Difference betwen adjacent elements
- ***np.round***: Round each number to the nearest integer
- **np.cumprod**:	A cumulative product: for each element, multiply all elements so far
- **np.cumsum**:	A cumulative sum: for each element, add all elements so far
- **np.exp**: Exponentiate each element
- **np.log**:	Take the natural logarithm of each element
- **np.sqrt**:	Take the square root of each element
- **np.sort**:	Sort the elements

Read more about this package from:
- https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference
- https://www.inferentialthinking.com/chapters/05/1/Arrays.html

In [ ]:
# Use numpy to compute the diff
import numpy as np
np.diff(highs)

array([0.69 , 0.34 , 0.692])

In [ ]:
np.sum(highs)

50.897999999999996

### Ranges
Ranges represent collections that are either increasing or decreasing by a regule interval

**np.arange** is used to define range. It takes 2 optional arguments - start=0, step=1. size is compulsor

Usages:
- np.arange({end})
- np.arange([start},{end})
- np.arange({start},{end},{step})

In [ ]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.arange(2, 8, 2)

array([2, 4, 6])

In [ ]:
np.arange(1.6, -2.9, -0.3)

array([ 1.6,  1.3,  1. ,  0.7,  0.4,  0.1, -0.2, -0.5, -0.8, -1.1, -1.4,
       -1.7, -2. , -2.3, -2.6])

### Access items in an array
- Use the item function for the array

In [ ]:
highs.item(2)

12.894

In [ ]:
reduced_array = highs - 2
highs - reduced_array

array([2., 2., 2., 2.])

### Using  the datascience Table()
Most datasets you will work with are represented as tables. 

Tables are identified by:
- A sequence of named columns
- A sequence of rows

Before working with a table, it is preferable to import all functions from the datascience module

**Full documentation reference**: http://data8.org/datascience/tables.html

In [ ]:
# We can create a single column table
Table().with_columns("Years", make_array(2015,2016,2017,2018,2019,2020))

Years
2015
2016
2017
2018
2019
2020

In [ ]:
# We can equally make a two column table.
students = Table().with_columns(
    "Year", make_array(2015, 2016, 2017, 2018, 2019, 2020),
    "Graduate", make_array("Qian", "Li", "Mu", "Chen", "Lee", "Yuri")
)

students

Year | Graduate
2015 | Qian
2016 | Li
2017 | Mu
2018 | Chen
2019 | Lee
2020 | Yuri

In [ ]:
# Add column to an existing table
students.with_columns(
    "length", make_array(8, 15, 28, 17, 7, 1)
)

Year | Graduate | length
2015 | Qian     | 8
2016 | Li       | 15
2017 | Mu       | 28
2018 | Chen     | 17
2019 | Lee      | 7
2020 | Yuri     | 1

In [ ]:
# Read the salaries CSV in our project library
# Note: every file that is part of the project folder is linked to the repository
salaries = Table.read_table("https://raw.githubusercontent.com/beneze/Datasets/master/SFSalaries2011_2014.csv")
salaries

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2822: DtypeWarning: Columns (3,4,5,6,12) have mixed types.Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):


Id   | EmployeeName       | JobTitle                                       | BasePay   | OvertimePay | OtherPay  | Benefits | TotalPay | TotalPayBenefits | Year | Notes | Agency        | Status
1    | NATHANIEL FORD     | GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY | 167411.18 | 0.0         | 400184.25 | nan      | 567595   | 567595           | 2011 | nan   | San Francisco | nan
2    | GARY JIMENEZ       | CAPTAIN III (POLICE DEPARTMENT)                | 155966.02 | 245131.88   | 137811.38 | nan      | 538909   | 538909           | 2011 | nan   | San Francisco | nan
3    | ALBERT PARDINI     | CAPTAIN III (POLICE DEPARTMENT)                | 212739.13 | 106088.18   | 16452.6   | nan      | 335280   | 335280           | 2011 | nan   | San Francisco | nan
4    | CHRISTOPHER CHONG  | WIRE ROPE CABLE MAINTENANCE MECHANIC           | 77916.0   | 56120.71    | 198306.9  | nan      | 332344   | 332344           | 2011 | nan   | San Francisco | nan
5    | PATRICK GARDNER    | DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   | 134401.6  | 9737.0      | 182234.59 | nan      | 326373   | 326373           | 2011 | nan   | San Francisco | nan
6    | DAVID SULLIVAN     | ASSISTANT DEPUTY CHIEF II                      | 118602.0  | 8601.0      | 189082.74 | nan      | 316286   | 316286           | 2011 | nan   | San Francisco | nan
7    | ALSON LEE          | BATTALION CHIEF, (FIRE DEPARTMENT)             | 92492.01  | 89062.9     | 134426.14 | nan      | 315981   | 315981           | 2011 | nan   | San Francisco | nan
8    | DAVID KUSHNER      | DEPUTY DIRECTOR OF INVESTMENTS                 | 256576.96 | 0.0         | 51322.5   | nan      | 307899   | 307899           | 2011 | nan   | San Francisco | nan
9    | MICHAEL MORRIS     | BATTALION CHIEF, (FIRE DEPARTMENT)             | 176932.64 | 86362.68    | 40132.23  | nan      | 303428   | 303428           | 2011 | nan   | San Francisco | nan
10   | JOANNE HAYES-WHITE | CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)         | 285262.0  | 0.0         | 17115.73  | nan      | 302378   | 302378           | 2011 | nan   | San Francisco | nan
... (148644 rows omitted)

In [ ]:
# Get the size of the table
print("Table size - rows:%d, columns:%d" % (salaries.num_rows, salaries.num_columns))

Table size - rows:148654, columns:13


In [ ]:
# Get the columns
salaries.labels

('Id',
 'EmployeeName',
 'JobTitle',
 'BasePay',
 'OvertimePay',
 'OtherPay',
 'Benefits',
 'TotalPay',
 'TotalPayBenefits',
 'Year',
 'Notes',
 'Agency',
 'Status')

In [ ]:
# Change some of the column names
renamed = salaries.relabeled("TotalPayBenefits", "TotalBenefits")
renamed

Id   | EmployeeName       | JobTitle                                       | BasePay   | OvertimePay | OtherPay  | Benefits | TotalPay | TotalBenefits | Year | Notes | Agency        | Status
1    | NATHANIEL FORD     | GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY | 167411.18 | 0.0         | 400184.25 | nan      | 567595   | 567595        | 2011 | nan   | San Francisco | nan
2    | GARY JIMENEZ       | CAPTAIN III (POLICE DEPARTMENT)                | 155966.02 | 245131.88   | 137811.38 | nan      | 538909   | 538909        | 2011 | nan   | San Francisco | nan
3    | ALBERT PARDINI     | CAPTAIN III (POLICE DEPARTMENT)                | 212739.13 | 106088.18   | 16452.6   | nan      | 335280   | 335280        | 2011 | nan   | San Francisco | nan
4    | CHRISTOPHER CHONG  | WIRE ROPE CABLE MAINTENANCE MECHANIC           | 77916.0   | 56120.71    | 198306.9  | nan      | 332344   | 332344        | 2011 | nan   | San Francisco | nan
5    | PATRICK GARDNER    | DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   | 134401.6  | 9737.0      | 182234.59 | nan      | 326373   | 326373        | 2011 | nan   | San Francisco | nan
6    | DAVID SULLIVAN     | ASSISTANT DEPUTY CHIEF II                      | 118602.0  | 8601.0      | 189082.74 | nan      | 316286   | 316286        | 2011 | nan   | San Francisco | nan
7    | ALSON LEE          | BATTALION CHIEF, (FIRE DEPARTMENT)             | 92492.01  | 89062.9     | 134426.14 | nan      | 315981   | 315981        | 2011 | nan   | San Francisco | nan
8    | DAVID KUSHNER      | DEPUTY DIRECTOR OF INVESTMENTS                 | 256576.96 | 0.0         | 51322.5   | nan      | 307899   | 307899        | 2011 | nan   | San Francisco | nan
9    | MICHAEL MORRIS     | BATTALION CHIEF, (FIRE DEPARTMENT)             | 176932.64 | 86362.68    | 40132.23  | nan      | 303428   | 303428        | 2011 | nan   | San Francisco | nan
10   | JOANNE HAYES-WHITE | CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)         | 285262.0  | 0.0         | 17115.73  | nan      | 302378   | 302378        | 2011 | nan   | San Francisco | nan
... (148644 rows omitted)

### Manipulating Table columns

- Use table.column({Name}) to access the column with the label {Name}
- Use table.column({Index}) to access a column based on the index

In [ ]:
renamed.column("TotalBenefits")

array([567595.43, 538909.28, 335279.91, ...,      0.  ,      0.  ,
         -618.13])

In [ ]:
# pull the 4th column
renamed.column(3)

array(['167411.18', '155966.02', '212739.13', ..., 'Not Provided',
       'Not Provided', '0.00'], dtype='<U32')

In [ ]:
# Add a new column, say a calculated column - Deviation from mean
average_benefit = renamed.column("TotalBenefits").mean()

table_with_deviation = renamed.with_columns(
    'Deviation from avg', renamed.column("TotalBenefits") - average_benefit
)

table_with_deviation


Id   | EmployeeName       | JobTitle                                       | BasePay   | OvertimePay | OtherPay  | Benefits | TotalPay | TotalBenefits | Year | Notes | Agency        | Status | Deviation from avg
1    | NATHANIEL FORD     | GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY | 167411.18 | 0.0         | 400184.25 | nan      | 567595   | 567595        | 2011 | nan   | San Francisco | nan    | 473903
2    | GARY JIMENEZ       | CAPTAIN III (POLICE DEPARTMENT)                | 155966.02 | 245131.88   | 137811.38 | nan      | 538909   | 538909        | 2011 | nan   | San Francisco | nan    | 445217
3    | ALBERT PARDINI     | CAPTAIN III (POLICE DEPARTMENT)                | 212739.13 | 106088.18   | 16452.6   | nan      | 335280   | 335280        | 2011 | nan   | San Francisco | nan    | 241587
4    | CHRISTOPHER CHONG  | WIRE ROPE CABLE MAINTENANCE MECHANIC           | 77916.0   | 56120.71    | 198306.9  | nan      | 332344   | 332344        | 2011 | nan   | San Francisco | nan    | 238651
5    | PATRICK GARDNER    | DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   | 134401.6  | 9737.0      | 182234.59 | nan      | 326373   | 326373        | 2011 | nan   | San Francisco | nan    | 232681
6    | DAVID SULLIVAN     | ASSISTANT DEPUTY CHIEF II                      | 118602.0  | 8601.0      | 189082.74 | nan      | 316286   | 316286        | 2011 | nan   | San Francisco | nan    | 222593
7    | ALSON LEE          | BATTALION CHIEF, (FIRE DEPARTMENT)             | 92492.01  | 89062.9     | 134426.14 | nan      | 315981   | 315981        | 2011 | nan   | San Francisco | nan    | 222288
8    | DAVID KUSHNER      | DEPUTY DIRECTOR OF INVESTMENTS                 | 256576.96 | 0.0         | 51322.5   | nan      | 307899   | 307899        | 2011 | nan   | San Francisco | nan    | 214207
9    | MICHAEL MORRIS     | BATTALION CHIEF, (FIRE DEPARTMENT)             | 176932.64 | 86362.68    | 40132.23  | nan      | 303428   | 303428        | 2011 | nan   | San Francisco | nan    | 209735
10   | JOANNE HAYES-WHITE | CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)         | 285262.0  | 0.0         | 17115.73  | nan      | 302378   | 302378        | 2011 | nan   | San Francisco | nan    | 208685
... (148644 rows omitted)

## SELECTing rows
The Table.select() function is the most common way of selecting columns from a table. 
There are also times when it's better to simply drop the columns you don't need

In [ ]:
# Selecting some columns from a table
table_with_deviation.select("TotalBenefits", "Id")

TotalBenefits | Id
567595        | 1
538909        | 2
335280        | 3
332344        | 4
326373        | 5
316286        | 6
315981        | 7
307899        | 8
303428        | 9
302378        | 10
... (148644 rows omitted)

In [ ]:
# Same can be achieved using the index
table_with_deviation.select(2,5)

JobTitle                                       | OtherPay
GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY | 400184.25
CAPTAIN III (POLICE DEPARTMENT)                | 137811.38
CAPTAIN III (POLICE DEPARTMENT)                | 16452.6
WIRE ROPE CABLE MAINTENANCE MECHANIC           | 198306.9
DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   | 182234.59
ASSISTANT DEPUTY CHIEF II                      | 189082.74
BATTALION CHIEF, (FIRE DEPARTMENT)             | 134426.14
DEPUTY DIRECTOR OF INVESTMENTS                 | 51322.5
BATTALION CHIEF, (FIRE DEPARTMENT)             | 40132.23
CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)         | 17115.73
... (148644 rows omitted)

In [ ]:
# Drop the notes column from our deviation table
table_with_deviation.drop("EmployeeName")

Id   | JobTitle                                       | BasePay   | OvertimePay | OtherPay  | Benefits | TotalPay | TotalBenefits | Year | Notes | Agency        | Status | Deviation from avg
1    | GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY | 167411.18 | 0.0         | 400184.25 | nan      | 567595   | 567595        | 2011 | nan   | San Francisco | nan    | 473903
2    | CAPTAIN III (POLICE DEPARTMENT)                | 155966.02 | 245131.88   | 137811.38 | nan      | 538909   | 538909        | 2011 | nan   | San Francisco | nan    | 445217
3    | CAPTAIN III (POLICE DEPARTMENT)                | 212739.13 | 106088.18   | 16452.6   | nan      | 335280   | 335280        | 2011 | nan   | San Francisco | nan    | 241587
4    | WIRE ROPE CABLE MAINTENANCE MECHANIC           | 77916.0   | 56120.71    | 198306.9  | nan      | 332344   | 332344        | 2011 | nan   | San Francisco | nan    | 238651
5    | DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   | 134401.6  | 9737.0      | 182234.59 | nan      | 326373   | 326373        | 2011 | nan   | San Francisco | nan    | 232681
6    | ASSISTANT DEPUTY CHIEF II                      | 118602.0  | 8601.0      | 189082.74 | nan      | 316286   | 316286        | 2011 | nan   | San Francisco | nan    | 222593
7    | BATTALION CHIEF, (FIRE DEPARTMENT)             | 92492.01  | 89062.9     | 134426.14 | nan      | 315981   | 315981        | 2011 | nan   | San Francisco | nan    | 222288
8    | DEPUTY DIRECTOR OF INVESTMENTS                 | 256576.96 | 0.0         | 51322.5   | nan      | 307899   | 307899        | 2011 | nan   | San Francisco | nan    | 214207
9    | BATTALION CHIEF, (FIRE DEPARTMENT)             | 176932.64 | 86362.68    | 40132.23  | nan      | 303428   | 303428        | 2011 | nan   | San Francisco | nan    | 209735
10   | CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)         | 285262.0  | 0.0         | 17115.73  | nan      | 302378   | 302378        | 2011 | nan   | San Francisco | nan    | 208685
... (148644 rows omitted)

In [ ]:
# Selecting the top 15 records
table_with_deviation.show(15)

In [ ]:
# Sort the data from lowest to the highest deviation
table_with_deviation.sort("Deviation from avg").show(10)

In [ ]:
# Second run with the sort in descending order
table_with_deviation.sort("Deviation from avg", descending=True).show(5)

In [ ]:
# select the top row
table_with_deviation.take(0)

Id   | EmployeeName   | JobTitle                                       | BasePay   | OvertimePay | OtherPay  | Benefits | TotalPay | TotalBenefits | Year | Notes | Agency        | Status | Deviation from avg
1    | NATHANIEL FORD | GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY | 167411.18 | 0.0         | 400184.25 | nan      | 567595   | 567595        | 2011 | nan   | San Francisco | nan    | 473903

In [ ]:
# select the 2 - 8th row
table_with_deviation.take(np.arange(2, 8))

Id   | EmployeeName      | JobTitle                                     | BasePay   | OvertimePay | OtherPay  | Benefits | TotalPay | TotalBenefits | Year | Notes | Agency        | Status | Deviation from avg
3    | ALBERT PARDINI    | CAPTAIN III (POLICE DEPARTMENT)              | 212739.13 | 106088.18   | 16452.6   | nan      | 335280   | 335280        | 2011 | nan   | San Francisco | nan    | 241587
4    | CHRISTOPHER CHONG | WIRE ROPE CABLE MAINTENANCE MECHANIC         | 77916.0   | 56120.71    | 198306.9  | nan      | 332344   | 332344        | 2011 | nan   | San Francisco | nan    | 238651
5    | PATRICK GARDNER   | DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT) | 134401.6  | 9737.0      | 182234.59 | nan      | 326373   | 326373        | 2011 | nan   | San Francisco | nan    | 232681
6    | DAVID SULLIVAN    | ASSISTANT DEPUTY CHIEF II                    | 118602.0  | 8601.0      | 189082.74 | nan      | 316286   | 316286        | 2011 | nan   | San Francisco | nan    | 222593
7    | ALSON LEE         | BATTALION CHIEF, (FIRE DEPARTMENT)           | 92492.01  | 89062.9     | 134426.14 | nan      | 315981   | 315981        | 2011 | nan   | San Francisco | nan    | 222288
8    | DAVID KUSHNER     | DEPUTY DIRECTOR OF INVESTMENTS               | 256576.96 | 0.0         | 51322.5   | nan      | 307899   | 307899        | 2011 | nan   | San Francisco | nan    | 214207

In [ ]:
# select rows based on a condition. For example, get the top benefit earners 
ninety_percentitle_benefit = np.percentile(renamed.column("TotalBenefits"), 98)
renamed.where("TotalBenefits", are.above(ninety_percentitle_benefit)).sort("TotalBenefits", True)

# You should notice that the returned records is 2% of the total.

Id     | EmployeeName         | JobTitle                                       | BasePay   | OvertimePay | OtherPay  | Benefits | TotalPay | TotalBenefits | Year | Notes | Agency        | Status
1      | NATHANIEL FORD       | GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY | 167411.18 | 0.0         | 400184.25 | nan      | 567595   | 567595        | 2011 | nan   | San Francisco | nan
2      | GARY JIMENEZ         | CAPTAIN III (POLICE DEPARTMENT)                | 155966.02 | 245131.88   | 137811.38 | nan      | 538909   | 538909        | 2011 | nan   | San Francisco | nan
110532 | David Shinn          | Deputy Chief 3                                 | 129150.01 | 0.0         | 342802.63 | 38780.04 | 471953   | 510733        | 2014 | nan   | San Francisco | PT
110533 | Amy P Hart           | Asst Med Examiner                              | 318835.49 | 10712.95    | 60563.54  | 89540.23 | 390112   | 479652        | 2014 | nan   | San Francisco | FT
110534 | William J Coaker Jr. | Chief Investment Officer                       | 257340.0  | 0.0         | 82313.7   | 96570.66 | 339654   | 436224        | 2014 | nan   | San Francisco | PT
72926  | Gregory P Suhr       | Chief of Police                                | 319275.01 | 0.0         | 20007.06  | 86533.21 | 339282   | 425815        | 2013 | nan   | San Francisco | nan
72927  | Joanne M Hayes-White | Chief, Fire Department                         | 313686.01 | 0.0         | 23236.0   | 85431.39 | 336922   | 422353        | 2013 | nan   | San Francisco | nan
110535 | Gregory P Suhr       | Chief of Police                                | 307450.04 | 0.0         | 19266.72  | 91302.46 | 326717   | 418019        | 2014 | nan   | San Francisco | FT
110536 | Joanne M Hayes-White | Chief, Fire Department                         | 302068.0  | 0.0         | 24165.44  | 91201.66 | 326233   | 417435        | 2014 | nan   | San Francisco | FT
110537 | Ellen G Moffatt      | Asst Med Examiner                              | 270222.04 | 6009.22     | 67956.2   | 71580.48 | 344187   | 415768        | 2014 | nan   | San Francisco | FT
... (2964 rows omitted)

In [ ]:
# Select records where the total pay equals the total benefits
renamed.where("TotalBenefits", are.equal_to("TotalPay")).show()

In [ ]:
# Pick up chief related jobs
renamed.where("JobTitle", are.containing("Chief")).where("BasePay", are.above("10000")).show(5)

In [ ]:
# Read the population data from a URL
data = 'http://www2.census.gov/programs-surveys/popest/datasets/2010-2015/national/asrh/nc-est2015-agesex-res.csv'
full_census_table = Table.read_table(data)

# Select the sex  and age and rename the 2010 and 2014 estimates
partial_census_table = full_census_table.select('SEX', 'AGE', 'POPESTIMATE2010', 'POPESTIMATE2014').relabeled('POPESTIMATE2010', '2010').relabeled('POPESTIMATE2014', '2014')

# Compute the population change
change = partial_census_table.column("2014") - partial_census_table.column("2010")

# Add the change column
census = partial_census_table.with_columns(
    'Change', change,
    'Percent Change', change/partial_census_table.column("2010")
)
census.set_format("Percent Change", PercentFormatter)
census.sort("AGE", descending=True)

SEX  | AGE  | 2010      | 2014      | Change  | Percent Change
2    | 999  | 157258820 | 161952064 | 4693244 | 2.98%
1    | 999  | 152088043 | 156955337 | 4867294 | 3.20%
0    | 999  | 309346863 | 318907401 | 9560538 | 3.09%
2    | 100  | 45058     | 58008     | 12950   | 28.74%
1    | 100  | 9352      | 13618     | 4266    | 45.62%
0    | 100  | 54410     | 71626     | 17216   | 31.64%
2    | 99   | 26074     | 32517     | 6443    | 24.71%
1    | 99   | 6104      | 8951      | 2847    | 46.64%
0    | 99   | 32178     | 41468     | 9290    | 28.87%
2    | 98   | 37532     | 46208     | 8676    | 23.12%
... (296 rows omitted)

## Mini-Project
***COVID-19 Trend Analysis ***
Covid-19 pandemic has hit the world. There are publicly available datasets that tracks the infection across the globe. 

Use one of such dataset to analysis and provide insights on the following questions:
- How many countries have COVID-19 infections?
- What are the worst hit countries?
- Which countries have the worst date rates?
- Which countries have the worst deaths?
- Provie a summary of the active and confirmed cases?

In [ ]:
from datetime import date
from datetime import timedelta


In [ ]:
# Read the latest covid-19 from a URL
covid_19_data = Table.read_table('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-05-2020.csv').sort("Active", descending=True)
covid_19_data

FIPS  | Admin2      | Province_State   | Country_Region | Last_Update         | Lat      | Long_    | Confirmed | Deaths | Recovered | Active | Combined_Key                | Incidence_Rate | Case-Fatality_Ratio
90004 | Unassigned  | Arizona          | US             | 2020-09-06 04:28:33 | nan      | nan      | 1         | 1      | 0         | nan    | Unassigned, Arizona, US     | nan            | 100
nan   | nan         | Unknown          | Chile          | 2020-09-06 04:28:33 | nan      | nan      | 54        | 1      | 54        | nan    | Unknown, Chile              | nan            | 1.85185
nan   | nan         | Diamond Princess | Canada         | 2020-09-06 04:28:33 | nan      | nan      | 0         | 1      | 0         | nan    | Diamond Princess, Canada    | nan            | nan
nan   | nan         | Lima             | Peru           | 2020-09-06 04:28:33 | -11.7665 | -76.6045 | 318822    | 13167  | 0         | 305655 | Lima, Peru                  | 2999.69        | 4.12989
nan   | nan         | England          | United Kingdom | 2020-09-06 04:28:33 | 52.3555  | -1.1743  | 297071    | 36892  | 0         | 260179 | England, United Kingdom     | 530.7          | 12.4186
6037  | Los Angeles | California       | US             | 2020-09-06 04:28:33 | 34.3083  | -118.228 | 247542    | 6000   | 0         | 241542 | Los Angeles, California, US | 2465.78        | 2.42383
nan   | nan         | nan              | France         | 2020-09-06 04:28:33 | 46.2276  | 2.2137   | 329353    | 30575  | 73866     | 224912 | France                      | 504.574        | 9.28335
nan   | nan         | Maharashtra      | India          | 2020-09-06 04:28:33 | 19.4498  | 76.1082  | 883862    | 26276  | 636574    | 221012 | Maharashtra, India          | 717.745        | 2.97286
12086 | Miami-Dade  | Florida          | US             | 2020-09-06 04:28:33 | 25.6112  | -80.5517 | 161018    | 2650   | 0         | 158368 | Miami-Dade, Florida, US     | 5926.45        | 1.64578
nan   | nan         | Sao Paulo        | Brazil         | 2020-09-06 04:28:33 | -23.5505 | -46.6333 | 853085    | 31313  | 680217    | 141555 | Sao Paulo, Brazil           | 1857.8         | 3.67056
... (3944 rows omitted)

In [ ]:
# How many countries have COVID-19
countries = covid_19_data.column("Country_Region")
uniques = np.unique(countries, return_counts=False)
uniques.size

188

In [ ]:
# Group the COVID-19 data by the country
covid19_grouped = covid_19_data.group("Country_Region", sum).sort("Active sum", True).select(
    'Country_Region', 'Confirmed sum', 'Deaths sum', 'Recovered sum', "Active sum"
 ).relabeled('Confirmed sum', 'confirmed').relabeled('Deaths sum', 'deaths').relabeled('Recovered sum', 'recovered').relabeled('Active sum', 'active')
covid19_grouped

Country_Region | confirmed | deaths | recovered | active
US             | 6244970   | 188538 | 2302187   | nan
Chile          | 420434    | 11551  | 392967    | nan
Canada         | 133511    | 9192   | 117968    | nan
India          | 4113811   | 70626  | 3180865   | 862320
Brazil         | 4123000   | 126203 | 3498999   | 497798
Spain          | 498989    | 29418  | 150376    | 319195
United Kingdom | 346513    | 41638  | 1806      | 303069
France         | 347267    | 30730  | 87927     | 228610
Russia         | 1017131   | 17707  | 835884    | 163540
Peru           | 676848    | 29554  | 498523    | 148771
... (178 rows omitted)

In [ ]:
# Calculate and add the death rate
data_rate_table = covid19_grouped.with_columns(
    'date rate', covid19_grouped.column("deaths")/covid19_grouped.column("confirmed")
)
data_rate_table.set_format("date rate", PercentFormatter)
data_rate_table.sort("date rate", descending=False)

Country_Region                   | confirmed | deaths | recovered | active | date rate
Bhutan                           | 228       | 0      | 150       | 78     | 0.00%
Eritrea                          | 330       | 0      | 295       | 35     | 0.00%
Mongolia                         | 310       | 0      | 296       | 14     | 0.00%
Seychelles                       | 136       | 0      | 127       | 9      | 0.00%
Dominica                         | 22        | 0      | 18        | 4      | 0.00%
Saint Vincent and the Grenadines | 61        | 0      | 58        | 3      | 0.00%
Timor-Leste                      | 27        | 0      | 25        | 2      | 0.00%
Cambodia                         | 274       | 0      | 272       | 2      | 0.00%
Laos                             | 22        | 0      | 21        | 1      | 0.00%
Saint Lucia                      | 26        | 0      | 26        | 0      | 0.00%
... (178 rows omitted)

In [ ]:
data_rate_table.sort("active", True)

Country_Region | confirmed | deaths | recovered | active | date rate
Canada         | 133511    | 9192   | 117968    | nan    | 6.88%
Chile          | 420434    | 11551  | 392967    | nan    | 2.75%
US             | 6244970   | 188538 | 2302187   | nan    | 3.02%
India          | 4113811   | 70626  | 3180865   | 862320 | 1.72%
Brazil         | 4123000   | 126203 | 3498999   | 497798 | 3.06%
Spain          | 498989    | 29418  | 150376    | 319195 | 5.90%
United Kingdom | 346513    | 41638  | 1806      | 303069 | 12.02%
France         | 347267    | 30730  | 87927     | 228610 | 8.85%
Russia         | 1017131   | 17707  | 835884    | 163540 | 1.74%
Peru           | 676848    | 29554  | 498523    | 148771 | 4.37%
... (178 rows omitted)

### Project summary
Provide the number of active and confirmed cases

In [ ]:
# Total active cases
active_cases = np.nan_to_num(data_rate_table.column("active")).sum()

# Total confirmed cases
confirmed_cases = np.nan_to_num(data_rate_table.column("confirmed")).sum()

print("Active cases: %d, Confirmed cases: %d" % (active_cases, confirmed_cases))

Active cases: 4299683, Confirmed cases: 26873146
